# Makefile
#

CC = gcc 
CFLAGS = -g -std=c99 -pedantic -W -Wall
CXX = g++
CXXFLAGS = -g -std=c++98 -pedantic -W -Wall
EXECS = max_sum1 max_sum2a max_sum2b max_sum3 max_sum4 maxsum \
	prob9 prob10 prob14 prob8 prob13

all: $(EXECS)

clean:
	-$(RM) *.o *.out core* $(EXECS)

.PHONY: all clean
