# Makefile
#

CC = gcc 
CFLAGS = -g -std=c99 -pedantic -W -Wall
CXX = g++
CXXFLAGS = -g -std=c++98 -pedantic -W -Wall

all: prob2 prob4 prob5 prob11

clean:
	-$(RM) *.o *.out core* prob2 prob4 prob5 prob11

.PHONY: all clean
