# Makefile
#

CC = gcc 
CFLAGS = -g -std=c99 -pedantic -W -Wall
CXX = g++
CXXFLAGS = -g -std=c++98 -pedantic -W -Wall

all: prob1 sortedrand prob7 

clean:
	-$(RM) *.o *.out core* prob1 sortedrand prob7

.PHONY: all clean
