
############## Beginning of Makefile #################


CC = gcc
CFLAGS = -ansi -pedantic -W -Wall -lm
RM = rm -rf


all: ex5


clean:
	$(RM) *.o ex5

.PHONY: all clean

############# End of Makefile #######################
