
############## Beginning of Makefile #################


CC = gcc
CFLAGS = -ansi -pedantic -W -Wall
RM = rm -rf


all: ex4


ex4: ex4.c
	$(CC) $(CFLAGS) $^ -o $@

clean:
	$(RM) *.o ex4

.PHONY: all clean

############# End of Makefile #######################
